#pragma config(Sensor, dgtl1,  ,               sensorQuadEncoder)
#pragma config(Motor,  port2,           fl,            tmotorVex393_MC29, openLoop, driveLeft, encoderPort, None)
#pragma config(Motor,  port3,           fr,            tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port4,           bl,            tmotorVex393_MC29, openLoop, driveLeft, encoderPort, dgtl1)
#pragma config(Motor,  port5,           br,            tmotorVex393_MC29, openLoop, driveRight)
#pragma config(Motor,  port7,           sl,            tmotorServoStandard, openLoop, driveLeft)
#pragma config(Motor,  port8,           sr,            tmotorServoStandard, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define VEX_LARGE_MOTOR_RPM 43.0
#define VEX_SMALL_MOTOR_RPM 90.0
#define MOTOR_RATIO (0.318)

enum DriveMode {
	directional,
	tank,
};

DriveMode drive_mode = tank;

void directional_drive() {
	float y = vexRT[Ch3];
	float x = vexRT[Ch4];
	float left = y + x;
	float right = y - x;

	motor[bl] = MOTOR_RATIO * left;
	motor[fl] = left;
	motor[br] = MOTOR_RATIO * right;
	motor[fr] = right;
}


void tank_drive() {
	motor[bl] = vexRT[Ch3] * MOTOR_RATIO;
	motor[fl] = vexRT[Ch3];
	motor[br] = MOTOR_RATIO * vexRT[Ch2];
	motor[fr] = vexRT[Ch3];
}

void controls() {
	switch (drive_mode) {
		case directional:
			directional_drive();
			break;
		default:
			tank_drive();
		break;
	}

	if (vexRT[Btn5U]){
		motor[sl] = 127;
		motor[sr] = 127;
	} else if (vexRT[Btn6U]) {
		motor[sl] = -127;
		motor[sr] = -127;
	}
}

void setup() {
}

task main()
{
	setup();
	while (1) {
		controls();
	}
}
