#pragma config(Motor,  port2,           bl,            tmotorServoContinuousRotation, openLoop, reversed, driveLeft)
#pragma config(Motor,  port3,           fl,            tmotorServoContinuousRotation, openLoop, reversed, driveLeft)
#pragma config(Motor,  port6,           servo,         tmotorServoStandard, openLoop)
#pragma config(Motor,  port8,           fr,            tmotorServoContinuousRotation, openLoop, driveRight)
#pragma config(Motor,  port9,           br,            tmotorServoContinuousRotation, openLoop, driveRight)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define VEX_LARGE_MOTOR_RPM 43.0
#define VEX_SMALL_MOTOR_RPM 90.0
//#define MOTOR_RATIO (0.318)
#define MOTOR_RATIO (0.36)

enum DriveMode {
	directional,
	tank,
	arcade,
};

DriveMode drive_mode = arcade;

void arcade_drive() {
	float pow = abs(vexRT[Ch3]) < 20 ? 0 : vexRT[Ch3];
	float turn = abs(vexRT[Ch1]) < 10 ? 0 : vexRT[Ch1];

	if (pow < 0) turn *= -1;

	float left = pow + turn;
	float right = pow - turn;
		if (vexRT[Btn5D]) {
		left = -left;
		right = -right;
	}

	if (vexRT[Btn5U]) {
		float tmp = left;
		left = right;
		right = tmp;
	}



	motor[br] = left;
	motor[fr] = left;
	motor[bl] = right;
	motor[fl] = right;
}

void directional_drive() {
	float y = abs(vexRT[Ch3]) < 10 ? 0 : vexRT[Ch3];
	float x = abs(vexRT[Ch4]) < 10 ? 0 : vexRT[Ch4];



	float left = y + x;
	float right = y - x;


	if (vexRT[Btn5U]) {
		float tmp = left;
		left = right;
		right = tmp;
	}

	if (vexRT[Btn5D]) {
		left = -left;
		right = -right;
	}

	//motor[bl] = MOTOR_RATIO * left;
	//motor[fl] = left;
	//motor[br] = MOTOR_RATIO * right;
	//motor[fr] = right;

	motor[br] = left;
	motor[fr] = left;
	motor[bl] = right;
	motor[fl] = right;
}


void tank_drive() {
	float left = abs(vexRT[Ch3]) < 10 ? 0 : vexRT[Ch3];
	float right = abs(vexRT[Ch2]) < 10 ? 0 : vexRT[Ch2];

	if (vexRT[Btn5U]) {
		left = -left;
		right = -right;
	}

	motor[br] = left;
	motor[fr] = left;
	motor[bl] = right;
	motor[fl] = right;
}

void change_drive() {
	if (vexRT[Btn7D]) {
		drive_mode = directional;
	} else if (vexRT[Btn7U]) {
		drive_mode = tank;
	} else if (vexRT[Btn7L]) {
		drive_mode = arcade;
	}
}
void controls() {
	change_drive();
	switch (drive_mode) {
		case directional:
			directional_drive();
			break;
		case tank:
			tank_drive();
			break;
		case arcade:
			arcade_drive();
			break;
		default:
			tank_drive();
		break;
	}

	if (vexRT[Btn6U]){
motor[servo] = -127;
	} else if (vexRT[Btn6D]) {
		motor[servo] = 250;
	}
}

void setup() {
	motor[servo] = 127;
}

task main()
{
	setup();
	while (1) {
		controls();
	}
}
